import { Sora, Inter } from "next/font/google";
import "./globals.css";
import { BackgroundRippleEffect } from "@/components/ui/background-ripple-effect";
import { PremiumStarsBackground } from "@/components/ui/premium-stars";
import { ThemeProvider } from "@/components/ThemeProvider";


const sora = Sora({
  variable: "--font-heading",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} ${inter.variable} antialiased relative`} 
      >
        <ThemeProvider>
          {/* Top gradient overlay */}
          <div className="fixed top-0 left-0 w-screen h-[40vh] z-10 pointer-events-none">
            <div className="block dark:hidden w-full h-full" style={{background: "linear-gradient(180deg, rgba(255,255,255,0.95) 0%, rgba(255,255,255,0.3) 60%, rgba(255,255,255,0.0) 100%)"}} />
            <div className="hidden dark:block w-full h-full" style={{background: "linear-gradient(180deg, rgba(0,0,0,0.95) 0%, rgba(0,0,0,0.3) 60%, rgba(0,0,0,0.0) 100%)"}} />
          </div>
          <BackgroundRippleEffect
            rows={8}
            cols={27}
            cellSize={90}
          />
          <div className="fixed inset-0 overflow-hidden pointer-events-none z-10 max-w-full w-full left-0 right-0">
            <PremiumStarsBackground />
          </div>
          <div className="relative z-20">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
